/*
 * Copyright (c) 2020 Sieve
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export enum VmOperation {
    ADD_R_R,
    ADD_R_I,
    SUB_R_R,
    SUB_R_I,
    MUL_R_R,
    MUL_R_I,
    DIV_R_R,
    DIV_R_I,
    MOD_R_R,
    MOD_R_I,
    MOV_R_R,
    MOV_R_I,
    MOV_R_M1,
    MOV_R_M2,
    MOV_R_M4,
    MOV_R_M8,
    MOV_M1_R,
    MOV_M2_R,
    MOV_M4_R,
    MOV_M8_R,
    MOV_R_RO_1,
    MOV_R_RO_2,
    MOV_R_RO_4,
    MOV_R_RO_8,
    MOV_RO_R_1,
    MOV_RO_R_2,
    MOV_RO_R_4,
    MOV_RO_R_8,
    CMP_R_R,
    CMP_R_I,
    AND_R_R,
    OR_R_R,
    LOGICAL_NOT,
    BITWISE_NOT,
    SET_E,
    SET_NE,
    SET_LT,
    SET_LE,
    SET_GT,
    SET_GE,
    PUSH_I,
    PUSH,
    POP,
    CALL,
    JMP,
    JZ,
    JNZ,
    RET,
}